import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
// import { Toaster } from "@/components/ui/sonner"
import { Github } from "lucide-react";


import "./globals.css";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="grid grid-rows-[1fr_20px] items-center justify-items-center min-h-screen p-3 pb-20 gap-2 sm:p-10 font-[family-name:var(--font-geist-sans)]">
                    <main className="flex flex-col gap-2 row-start-1 items-center sm:w-4/5 w-full h-full  sm:items-stretch">
                        {children}
                    </main>
                    <Toaster />
                    <footer className="row-start-5 flex gap-6 flex-wrap items-center justify-center">
                        <a
                            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                            href="https://github.com/RoundRonin"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            <Github />
                            My GitHub
                        </a>
                    </footer>
                </div>
            </body>
        </html >
    );
}
