FROM node:latest

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# COPY tailwind.config.ts postcss.config.mjs ./

COPY . .

EXPOSE 3000

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
